# Generated by Django 4.1.3 on 2023-01-03 21:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_rename_author_blog_autor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nuevo_sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_locacion', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('comentario', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
