# Generated by Django 4.1.3 on 2023-01-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0005_alter_blog_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='opinion',
        ),
    ]
