# Generated by Django 4.1.3 on 2023-01-08 15:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_remove_blog_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='opinion',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='test'),
            preserve_default=False,
        ),
    ]
