# Generated by Django 4.1.3 on 2023-01-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0009_alter_blog_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha_publicacion',
            field=models.DateTimeField(verbose_name='XYZ DateTime'),
        ),
    ]
