# Generated by Django 4.1.3 on 2023-01-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0010_alter_blog_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha_publicacion',
            field=models.DateField(verbose_name='XYZ Date'),
        ),
    ]
