# Generated by Django 4.1.3 on 2023-01-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_blog_delete_blog_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_blog',
        ),
    ]
